version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    mem_limit: 2048m
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.17.9
    ports:
      - '5601:5601'
